<Project Sdk="Aspire.AppHost.Sdk/13.1.0">

  <ItemGroup>
    <ProjectReference Include="..\MusicShare.Api\MusicShare.Api.csproj" />
    <ProjectReference Include="..\MusicShare.Worker\MusicShare.Worker.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Azure.AppContainers" Version="13.1.0" />
    <PackageReference Include="Aspire.Hosting.MongoDB" Version="13.1.0" />
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.1.0" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" Version="13.1.0" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);ASPIREACADOMAINS001</NoWarn>
    <UserSecretsId>cc3bed15-222b-471f-b536-4109d9639f5f</UserSecretsId>
  </PropertyGroup>

</Project>
